# backend/app/config/homepage.yaml
title: "BenchMate Platform"
welcome_message: "Welcome to BenchMate." # overarching platform messages, social links, or navigation elements that connect different parts of BenchMate
