# backend/app/config/benchtop/biology/omics/transcriptomics/bulk-rna-seq/volcano.yaml
expected_columns:
  gene: "gene"
  log2fc: "logfc"            # Default expected fold change column name; may be overridden.
  pvalue: "pvalue"         # Default expected p-value column name.
default_plot: "volcano"
available_plots:
  - "volcano"
thresholds:
  log2fc: 1.0
  pvalue: 0.05
colors:
  up: "#FF0000"
  down: "#0000FF"
  neutral: "#B0B0B0"
legend:
  labels:
    up: "Upregulated"
    down: "Downregulated"
    neutral: "No Change"
  title: "Regulation"
  position: "best"
axis:
  x_min: -5.0
  x_max: 5.0
  y_min: 0.0
  y_max: 10.0
  log_scale_y: false
layout:
  add_footer: true
  show_grid: true
  plot_width: 8
  plot_height: 6
  show_borders: false
auto_label:
  top_n_up: 0
  top_n_down: 0
graph:
  title: "Volcano Plot"
metadata:
  organism: "Homo sapiens"
  tissue: "colon"
  experiment_type: "treated_vs_control"
